_target_           : lightning.pytorch.trainer.Trainer
default_root_dir   : ${paths.output_dir}

min_epochs         : 35 #15 #prevents early stopping
max_epochs         : 100 #30

enable_progress_bar: True
log_every_n_steps  : 1000
accelerator        : gpu
devices            : -1