path:
  absolute_path: ${base_dir:x}
  dataset_dir: ${path.absolute_path}/../slakh2100
  train_dir: ${path.dataset_dir}/train
  test_dir: ${path.dataset_dir}/test
  val_dir: ${path.dataset_dir}/validation
  checkpoint_dir: ${path.absolute_path}/checkpoint
  plot_dir: ${path.absolute_path}/plots
  codebook_file: ${path.absolute_path}/codebook.csv
model:
  num_hidden: 128
  num_residual_hidden: 32
  num_residual_layer: 2
  embedding_dim: 64
  num_embeddings: 512
  commitment_cost: 1
  learning_rate: 1e-4
data:
  target_sample_rate: 25000
  target_frame_length_sec: 3
trainer:
  max_epochs: 60
  min_epochs: 30
  batch_size: 64
  profiler: "simple"
  early_stopping_patience: 10
  early_stopping_monitor: "validation/loss"
  early_stopping_monitor_mode: "min"
  load_from_checkpoint: False
logger:
  wandb: True
  wandb_name: "VQ-VAE - MSE/22 - Test2"
  wandb_project_name: "DLAI Experiments"
  wandb_offline: False
  version: 'None'
