path:
  absolute_path: ${base_dir:x}
  dataset_dir: ${path.absolute_path}/slakh2100
  train_dir: ${path.dataset_dir}/train
  test_dir: ${path.dataset_dir}/test
  val_dir: ${path.dataset_dir}/validation
  logging_dir: ${path.absolute_path}/logging
  output_dir: ${path.absolute_path}/samples
  checkpoint_dir: ${path.absolute_path}/checkpoint
model:
  num_hidden: 128
  num_residual_hidden: 32
  num_residual_layer: 2
  embedding_dim: 64
  num_embeddings: 512
  commitment_cost: 0.25
  learning_rate: 1e-4
data:
  target_sample_rate: 16000
  target_frame_length_sec: 3
trainer:
  max_epochs: 200
  batch_size: 64
  profiler: "simple"
  early_stopping_patience: 5
  early_stopping_monitor: "val_loss"
  early_stopping_monitor_mode: "min"
logger:
  wandb: True
  wandb_project_name: "VQVAE_experiments"
  wandb_offline: False
