path:
  absolute_path: ${base_dir:x}
  dataset_dir: ${path.absolute_path}/../slakh2100
  train_dir: ${path.dataset_dir}/train
  test_dir: ${path.dataset_dir}/test
  val_dir: ${path.dataset_dir}/validation
  checkpoint_dir: ${path.absolute_path}/checkpoint
  plot_dir: ${path.absolute_path}/plots
  codebook_file: ${path.absolute_path}/codebook.csv
model:
  vqvae:
    num_hidden: 128
    num_residual_hidden: 32
    num_residual_layer: 2
    embedding_dim: 64
    num_embeddings: 512
    commitment_cost: 0.25
    learning_rate: 1e-4
  transformer:
    output_dim: ${eval:'${data.target_sample_rate} * ${data.target_frame_length_sec}'}
    input_dim: ${eval:'${model.transformer.output_dim} // 4'}
    num_layers: 4
    num_heads: 8
    hidden_dim: 512
    learning_rate: 1e-4
data:
  target_sample_rate: 25000
  target_frame_length_sec: 3
trainer:
  optimize: True
  max_epochs: 60
  min_epochs: 15
  batch_size: 64
  profiler: "simple"
  early_stopping_patience: 5
  early_stopping_monitor: "validation/loss"
  early_stopping_monitor_mode: "min"
  load_from_checkpoint: False
logger:
  wandb: False
  wandb_name: "VQVAE"
  wandb_project_name: "DLAI Experiments Hypertraining"
  wandb_offline: False
  version: 'None'
