name        : hydra_env

channels    :
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.*
  - torchvision=0.*
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - wandb
  - pip>=23
  - sox=14.*
  - torchaudio=2.*
  - pandas=2.*
  - umap-learn=0.*
  - seaborn=0.*
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils