name: hydra_lightning

channels:
  - pytorch
  - conda-forge
  - defaults
  -
dependencies:
  - python=3.10
  - pytorch=2.*
  - torchvision=0.*
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - wandb=0.16.*
  - pip>=23
  - pandas=2.1.*
  - torchaudio=2.1.*
  - matplotlib=3.8.*
  - umap-learn=0.5
  - seaborn=0.13.*
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
