bert:
  _target_      : src.model.bert.AudioBert
  learning_rate : 1e-4
  checkpoint_dir: ${paths.checkpoint_dir}
  sample_rate   : ${data.target_sample_rate}
  frame_length  : ${data.target_sample_duration}
  codebook      : ${paths.codebook_file}
  num_embedding : ${model.vqvae.num_embedding}