vqvae:
  _target_           : src.model.vqvae.VQVAE
  num_hidden         : 128
  num_residual_layer : 2
  num_residual_hidden: 32
  num_embedding      : 512
  embedding_dim      : 64
  commitment_cost    : 1
  learning_rate      : 1e-4
  sample_rate        : ${data.datamodule.target_sample_rate}
  checkpoint_dir     : ${paths.checkpoint_dir}
  codebook_file      : ${paths.codebook_file}