# https://wandb.ai

wandb:
  _target_ : lightning.pytorch.loggers.wandb.WandbLogger
  name     : "L2/0.2 masking"
  project  : "DLAI Transformer Hyper-tuning"
  save_dir : ${paths.output_dir}
  log_model: False # upload lightning ckpts
  offline  : False
  settings :
    init_timeout: 300
  version  : null # pass id to resume experiment