root_dir      : ${oc.env:PROJECT_ROOT} # path to root directory

work_dir      : ${hydra:runtime.cwd} # path to working directory

dataset_dir   : ${paths.root_dir}/../slakh2100  # path to dataset directory
train_dir     : ${paths.dataset_dir}/train # path to train dataset directory
test_dir      : ${paths.dataset_dir}/test # path to test dataset directory
val_dir       : ${paths.dataset_dir}/validation # path to validation dataset directory

output_dir    : ${hydra:runtime.output_dir} # path to output directory created by hydra
log_dir       : ${paths.output_dir}/logs/ # path to log directory
checkpoint_dir: ${paths.output_dir}/checkpoint # path to checkpoint directory
plot_dir      : ${paths.output_dir}/plot_dir # path to plot directory
codebook_file : ${paths.output_dir}/codebook.csv # path to codebook file