defaults:
  - _self_
  - datamodule: default
  - model: model
  - callbacks: [early_stopping, model_checkpoint]
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - hparams_search: null
  - hydra: default

train: True
test: False
seed: 14

ckpt_path: null # path to checkpoint
