# @package _global_

# order of defaults determines the order in which configs override each other
defaults :
  - _self_
  - data: default
  - model: model
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - debug: default

task_name: "train"

train    : True # train the model
test     : False # evaluate the model
ckpt_path: null # resume training from path
seed     : 14
