# @package _global_

# default debugging setup, will run the requested loop using 1 batch
# Logging and checkpointing is suppressed.
task_name: "debug"

# disable callbacks and loggers during debugging
callbacks: null
logger   : null

extras   :
  ignore_warnings: False
  enforce_tags   : False

# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
# sets level of all command line loggers to 'DEBUG'
hydra    :
  job_logging:
    root:
      level: DEBUG

trainer  :
  max_epochs         : 1
  accelerator        : cpu # debuggers don't like gpus
  devices            : 1 # debuggers don't like multiprocessing
  detect_anomaly     : true # raise exception if NaN or +/-inf is detected in any tensor
  fast_dev_run       : true
  profiler           : simple
  enable_progress_bar: False
  log_every_n_steps  : null
  limit_train_batches: 0.1
  limit_val_batches  : 0.1
  limit_test_batches : 0.1

data     :
  num_workers       : 0 # debuggers don't like multiprocessing
  pin_memory        : False # disable gpu memory pin
  batch_size        : 2
  persistent_workers: False